// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIJvE-nqDzEO_4lo2LAvf7MdNJ4lu7_Rk',
    appId: '1:400361248987:android:fb4dc7f8851703aa5614fe',
    messagingSenderId: '400361248987',
    projectId: 'inventorytis',
    storageBucket: 'inventorytis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWlq3v93BxI7HgLQ2Z7LTkdFsda5Em0dc',
    appId: '1:400361248987:ios:cdad43b916bd84605614fe',
    messagingSenderId: '400361248987',
    projectId: 'inventorytis',
    storageBucket: 'inventorytis.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlekk8HBVrWWY2mYZQBibAasyHYJ9EaFI',
    appId: '1:400361248987:web:e5298f6b42b563295614fe',
    messagingSenderId: '400361248987',
    projectId: 'inventorytis',
    authDomain: 'inventorytis.firebaseapp.com',
    storageBucket: 'inventorytis.firebasestorage.app',
    measurementId: 'G-FSTLNLKL5S',
  );

}